# Generated by Django 4.2.2 on 2023-07-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0004_profileuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
