# Generated by Django 4.2.2 on 2023-08-03 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0005_alter_articlecomment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'نظر مقاله', 'verbose_name_plural': 'نظرات مقاله'},
        ),
        migrations.RemoveField(
            model_name='articlecomment',
            name='created_date',
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2023, 8, 3), verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
    ]
