# Generated by Django 4.2.2 on 2023-07-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0003_alter_sitesetting_site_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='site_logo',
            field=models.ImageField(upload_to='images/setting', verbose_name='لوگو سایت'),
        ),
    ]
