# Generated by Django 4.2.2 on 2023-07-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0004_alter_sitesetting_site_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('url', models.CharField(max_length=200, verbose_name='لینک اسلایدر')),
                ('url_title', models.CharField(max_length=200, verbose_name='عنوان لینک ')),
                ('logo', models.ImageField(upload_to='images/slider', verbose_name='تصویر اسلایدر')),
                ('is_active', models.BooleanField(verbose_name='فعال/غیر فعال')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
    ]
